### PR TITLE
macOS: Fix text insertion by modifier keys when using IME

### PR DESCRIPTION
**Pull request by page-down**
There is another situation when dealing with macOS input method modifier keys.
It is possible for the input method to call insertText and then continue to send the event to the program without intercepting it.

I have tested it and it works fine to insert text in this case too.

There is also a problem with this PR, if the input method inserts text immediately after the initial press of the modifier key when there is no markedText, then it will not work. A separate flag is needed to replace `handled` from `[inpctx handleEvent:event]` (which is meaningless).

But I haven't come across this kind of input method so far.

Please review if there is anything that needs to be adjusted.

### CODE REVIEW

**Comment by page-down** [comment]
To clarify, here is the relevant IME code for this case.

```objc
@implementation SquirrelInputController { //... }
- (BOOL)handleEvent:(NSEvent*)event client:(id)sender
{
    BOOL handled = NO; // ...
    switch (event.type) {
        case NSEventTypeFlagsChanged: { // ...
            if (changes & OSX_SHIFT_MASK) { // ...
                [self processKey:XK_Shift_L modifiers:(rime_modifiers | release_mask)];
            }
        } break;
        case NSEventTypeKeyDown: { // ...
            handled = [self processKey:rime_keycode modifiers:rime_modifiers]; // ...
        } break;
        // ...
    } // ...
    return handled;
}
```

The flag `handled = [inpctx handleEvent:event]` does not reflect whether insertText has been called or not.
I think it can be removed (replaced).

**Comment by kovidgoyal** [comment]
On Sat, Jan 22, 2022 at 09:16:08PM -0800, page-down wrote:
> The flag `handled = [inpctx handleEvent:event]` does not reflect whether insertText has been called or not.
> I think it can be removed (replaced).

If handled is false it would imply that the input context ignored the
event completely. It being true does not imply that insetText was
called, but in order for insertext to have been called, it must be true.

**Comment by page-down** [comment]
> If handled is false it would imply that the input context ignored the
> event completely.

I don't understand, why the following log exists when I test it.

Doesn't the value returned represent whether or not it was eventually marked as processed? Then IME can send insertText and return false to let the event flow to the next one, and the input context will return false if no one is marked as true in the end.

```text
-------------- flags changed -----------------
NSEvent: type=FlagsChanged loc=(322,171.016) time=16209.4 flags=0x100 win=0x7fd5ca72ebe0 winNum=933 ctxt=0x0 keyCode=56
flagsChanged: modifer: shift native_key: 0x38 (<noname>) glfw_key: 0xe061 mods: none 
---> [flagsChanged] call handled = [inpctx handleEvent:event]
---> [insertText] start, in_key_handler: 2

	insertText: k replacementRange: (9223372036854775807, 0)
---> [insertText] set marked_text_cleared_by_insert = true
sending text to kitty from insertText called from event loop: k
on_key_input: glfw key: 0x0 native_code: 0x0 action: RELEASE mods: none text: 'k' state: 2 committed pre-edit text: k
---> [flagsChanged] after inpctx handleEvent, handled: 0
Clearing pre-edit text
```

**Comment by kovidgoyal** [comment]
On Sat, Jan 22, 2022 at 10:18:14PM -0800, page-down wrote:
> > If handled is false it would imply that the input context ignored the
> > event completely.
> 
> I don't understand, why the following log exists when I test it.
> 
> Doesn't the value returned represent whether or not it was eventually marked as processed? Then IME can send insertText and return false to let the event flow to the next one, and the input context will return false if no one is marked as true in the end.

If that is the semantics of handled, then yes it should be removed.

**Pull request merged**
