### PR TITLE
Filter tic output to remove "older tic versions may treat the description field as an alias"

### PR DESCRIPTION
**Pull request by Luflosi**
Since you mentioned in #840 that you don't want to miss actually useful warnings from tic, I implemented a simple filter that ignores all messages that match a very specific regex.

### CODE REVIEW

**Comment by Luflosi** [comment]
I don't quite understand why the test failed. It does not seem to know the `text` argument of `subprocess.run` even though the docs say that function with the parameter exists since python 3.5 (which you told me is the minimum supported python version): https://docs.python.org/3/library/subprocess.html

**Comment by Luflosi** [comment]
And what is build-terminfo used for/when is it used?

**Comment by kovidgoyal** [comment]
according to the python docs, text was added in 3.7 not 3.5

```
Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.
```

Dont use text anyway. pythons encoding handling magic is a bad design. Just decode stderr using utf-8

**Comment by Luflosi** [comment]
Ah, I didn't notice that changelog. Now I just decode stderr using utf-8 like you suggested. I decode it after the `subprocess.run()` since the `encoding` parameter was introduced in python 3.6. I now also use a loop in case `tic` output multiple lines.

**Comment by Luflosi** [comment]
What is build-terminfo used for/when is it used?

**Comment by kovidgoyal** [comment]
to build the kitty terminfo files from source. It is used during the build process.

**Comment by kovidgoyal** [comment]
It is run manually to update the compiled terminfo files that are checked into version control, which is what allows kitty to be run directly from source. In setup.py it is run to generate the terminfo files that are added to the built kitty package.

**Comment by Luflosi** [comment]
Why does `setup.py` run `tic`? Can't it just copy the stuff from the `terminfo` directory? Now, that would not compile `kitty.terminfo` every time `package()` of `setup.py` is called, but do you want that? And if you want that, then wouldn't it be better to put the terminfo-compilation functionality of `package()` and `build-terminfo` into its own function in `terminfo.py`?

**Comment by kovidgoyal** [comment]
I do want it, and it is not complex enough to put into its own function.

**Pull request merged**
