### PR TITLE
macOS: Allow to customize Hide, Minimize, and Quit global menu shortcuts

### LINKED ISSUE #948: Remapping command+h on macos doesn't work
A mapping such as `map super+h previous_window` doesn't override the system's Hide shortcut, so pressing command+h hides Kitty. There's probably some way around this, not too sure what it is.

### PR DESCRIPTION
**Pull request by page-down**
All previously hard-coded shortcuts under macOS can be configured now.

Fixes #948

Please review, thanks.

### CODE REVIEW

**Comment by page-down** [comment]
Please do not merge yet, I found that sometimes when minimizing the window kitty will be unresponsive, still looking for the reason.

**Comment by page-down** [comment]
I have updated the PR and have not observed kitty hanging for now, please review, thanks.

However, I noticed another issue.
After running `boss.toggle_fullscreen()` it will print cocoa exception messages, for example after pressing the default shortcut `ctrl+cmd+f`.

Unfortunately, I spent some time, but still did not find the cause of the error.

**Comment by kovidgoyal** [comment]
On Tue, Dec 20, 2022 at 05:18:07AM -0800, page-down wrote:
> I have updated the PR and have not observed kitty hanging for now, please review, thanks.
> 
> However, I noticed another issue.
> After running `boss.toggle_fullscreen()` it will print cocoa exception messages, for example after pressing the default shortcut `ctrl+cmd+f`.
> 
> Unfortunately, I spent some time, but still did not find the cause of the error.

Are you saying this PR causes it or that it happens even without the PR?
I get no cocoa exceptions printed to stderr after pressing ctrl+cmd+f
what exception are you seeing?

**Comment by page-down** [comment]
It happens without the PR.
I also tested 0.26.5 from GitHub Release, and nightly.
macOS 13.1

It does not appear to be from:
`static void uncaughtExceptionHandler(NSException *exception)`
since there is only stack trace and no other text.

Example from the documentation:
https://sw.kovidgoyal.net/kitty/kittens/custom/#using-kittens-to-script-kitty-without-any-terminal-ui

```python
@result_handler(no_ui=True)
def handle_result(args: List[str], answer: str, target_window_id: int, boss: Boss) -> None:
    boss.toggle_fullscreen()
```

```shell
/Volumes/kitty-0.26.5/kitty.app/Contents/MacOS/kitty --config=NONE
```

```log
1   HIToolbox                           0x00007ff81cba4726 _ZN15MenuBarInstance22EnsureAutoShowObserverEv + 102
2   HIToolbox                           0x00007ff81cba42b8 _ZN15MenuBarInstance14EnableAutoShowEv + 52
3   HIToolbox                           0x00007ff81cb13cd7 _ZN15MenuBarInstance21UpdateAggregateUIModeE21MenuBarAnimationStylehhh + 1113
4   HIToolbox                           0x00007ff81cba4173 _ZN15MenuBarInstance19SetFullScreenUIModeEjj + 175
5   AppKit                              0x00007ff8166754b7 -[NSApplication _setPresentationOptions:instance:flags:] + 1145
6   AppKit                              0x00007ff8164ca165 -[NSApplication _updateFullScreenPresentationOptionsForInstance:] + 582
7   CoreFoundation                      0x00007ff8131e43f4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
8   CoreFoundation                      0x00007ff81327e43a ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                      0x00007ff81327e389 _CFXRegistrationPost + 536
10  CoreFoundation                      0x00007ff8131b7919 _CFXNotificationPost + 735
11  Foundation                          0x00007ff813ff1f2c -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
12  AppKit                              0x00007ff816675b28 spacesNotificationHandler + 119
13  SkyLight                            0x00007ff817e1374d _ZN12_GLOBAL__N_123notify_datagram_handlerEj15CGSDatagramTypePvmS1_ + 1030
14  SkyLight                            0x00007ff81812604a _ZN21CGSDatagramReadStream26dispatchMainQueueDatagramsEv + 202
15  SkyLight                            0x00007ff818125f71 ___ZN21CGSDatagramReadStream15mainQueueWakeupEv_block_invoke + 18
16  libdispatch.dylib                   0x00007ff812f927fb _dispatch_call_block_and_release + 12
17  libdispatch.dylib                   0x00007ff812f93a44 _dispatch_client_callout + 8
18  libdispatch.dylib                   0x00007ff812fa07b9 _dispatch_main_queue_drain + 952
19  libdispatch.dylib                   0x00007ff812fa03f3 _dispatch_main_queue_callback_4CF + 31
20  CoreFoundation                      0x00007ff81322d610 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
21  CoreFoundation                      0x00007ff8131edb90 __CFRunLoopRun + 2454
22  CoreFoundation                      0x00007ff8131ecb80 CFRunLoopRunSpecific + 560
23  HIToolbox                           0x00007ff81cb31766 RunCurrentEventLoopInMode + 292
24  HIToolbox                           0x00007ff81cb31576 ReceiveNextEventCommon + 679
25  HIToolbox                           0x00007ff81cb312b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
26  AppKit                              0x00007ff816338f33 _DPSNextEvent + 909
27  AppKit                              0x00007ff816337db4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
28  AppKit                              0x00007ff81632a3f7 -[NSApplication run] + 586
29  kitty.glfw-cocoa.so                 0x0000000104ef3d95 glfwRunMainLoop + 101
30  kitty.fast_data_types.so            0x000000010439d8dd kitty.fast_data_types.so + 30941
31  Python                              0x00000001030de173 method_vectorcall_NOARGS + 115
32  Python                              0x00000001031fd74c call_function + 172
33  Python                              0x00000001031fb1df _PyEval_EvalFrameDefault + 44543
34  Python                              0x00000001031eef99 _PyEval_EvalCode + 537
35  Python                              0x00000001030d00f3 _PyFunction_Vectorcall + 403
36  Python                              0x00000001031fd74c call_function + 172
37  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
38  Python                              0x00000001031eef99 _PyEval_EvalCode + 537
39  Python                              0x00000001030d00f3 _PyFunction_Vectorcall + 403
40  Python                              0x00000001030cf17f _PyObject_FastCallDictTstate + 95
41  Python                              0x00000001031540bb slot_tp_call + 187
42  Python                              0x00000001030ceea8 _PyObject_MakeTpCall + 136
43  Python                              0x00000001031fd7d7 call_function + 311
44  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
45  Python                              0x00000001030d003a _PyFunction_Vectorcall + 218
46  Python                              0x00000001031fd74c call_function + 172
47  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
48  Python                              0x00000001030d003a _PyFunction_Vectorcall + 218
49  Python                              0x00000001031fd74c call_function + 172
50  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
51  Python                              0x00000001030d003a _PyFunction_Vectorcall + 218
52  Python                              0x00000001031fd74c call_function + 172
53  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
54  Python                              0x00000001031eef99 _PyEval_EvalCode + 537
55  Python                              0x00000001031e9780 builtin_exec + 384
56  Python                              0x000000010312c2b3 cfunction_vectorcall_FASTCALL + 99
57  Python                              0x00000001031fd74c call_function + 172
58  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
59  Python                              0x00000001031eef99 _PyEval_EvalCode + 537
60  Python                              0x00000001030d00f3 _PyFunction_Vectorcall + 403
61  Python                              0x00000001031fd74c call_function + 172
62  Python                              0x00000001031fb2a5 _PyEval_EvalFrameDefault + 44741
63  Python                              0x00000001031eef99 _PyEval_EvalCode + 537
64  Python                              0x00000001030d00f3 _PyFunction_Vectorcall + 403
65  Python                              0x000000010328f971 pymain_run_module + 241
66  Python                              0x000000010328f0dc pymain_run_python + 604
67  Python                              0x000000010328ee37 Py_RunMain + 23
68  kitty                               0x00000001026ce3c3 main + 4771
69  kitty                               0x00000001026cd5e6 main + 1222
70  dyld                                0x00007ff812de0310 start + 2432
```

**Comment by page-down** [comment]
Sorry, I'm pretty sure this comes from the system framework and has nothing to do with kitty.
There is no implementation from the code that is problematic in any way.
However I have not found a way to work around it or a solution yet and will have to live with it for now.

**Pull request merged**
