### PR TITLE
Added new icons to the FAQ page

### PR DESCRIPTION
**Pull request by eccentric-j**
- Added the 2d winky terminal icon
- Added the 3d reinterpretation of the original

Have not worked with rst yet. How does one preview the build?

### CODE REVIEW

**Comment by page-down** [comment]
This will cause to load 1.7MB of new icon image data when opening the FAQ page.
The current maximum size of the other icons in the document page is only 350KB.

I personally recommend providing 256x256 compressed preview icons that are hosted in GitHub.

> ... How does one preview the build?

https://sw.kovidgoyal.net/kitty/build/

After building the documentation, you will be able to see the HTML files in `docs/_build/`.

**Comment by kovidgoyal** [comment]
You can also just preview in github itself, it has a basic rst renderer.
And yes please reduce the icon preview image sizes.

**Comment by eccentric-j** [comment]
I'll make an additional web-friendly, compressed version and make another PR to update those links.

Would there be any benefit to making it 512x512 so it won't look blurry on retina displays?

**Comment by page-down** [comment]
> ... making it 512x512 ...

Yes. That would be acceptable.

**Pull request merged**
