### PR TITLE
add background blur on macos

### PR DESCRIPTION
**Pull request by BIKA-C**
This is an attempt to add background blur to macos. I am not familiar to the code base and a little confused about how to properly read config. Any help would be appreciated. Here is a fixed blur radius preview:
image

### CODE REVIEW

**Comment by kovidgoyal** [comment]
This is a non-public API correct? And dont you have to set a color for the blur?  window.backgroundColor IIRC

Not to mention there is no generally applicable solution for this on other platforms that I know of. I am not very keen to add platform specific features that anyway use a private API and so may stop working at any time.

As for your actual implementation, move it into kitty/cocoa_window.m then you can access the config value as simply OPT(whatever).

**Comment by page-down** [comment]
@BIKA-C

You should use `NSVisualEffectView` and set the blending mode instead of using the private API.

**Comment by hungvx-dev** [comment]
> 

You can apply `NSVisualEffectView` to this PR.

**Comment by hungvx-dev** [comment]
@kovidgoyal You can update this PR and merge it for the next release. I very need this feature. Please help me.

**Comment by FormalSnake** [comment]
I need it too!

**Comment by hungvx-dev** [comment]
@FormalSnake Yes. Because, when using background opacity is below 0.8 then it will be difficult to see, eyestrain. So we need a degree of blur

Screenshot 2023-06-08 at 10 36 44

**Comment by kovidgoyal** [comment]
Kindly stop spamming my inbox. I already stated my concerns with this PR no one has addressed them. Come up with a proper PR and we can discuss further.

**Pull request closed without merging**
