### PR TITLE
Update symbol_map

### PR DESCRIPTION
**Pull request by rqel**
Update the symbol_map according to https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points/

### CODE REVIEW

**Comment by page-down** [comment]
The `U+F500-U+FD46` range contains Unicode ranges that should not be changed.
Make sure the Unicode mapping range is appropriate when updating.

**Comment by page-down** [comment]
Your updated `c` is lowercase and inconsistent with the others.

**Comment by rqel** [comment]
Yes you are right, but we should probably change U+F313 to U+F31C to reflect this: https://github.com/ryanoasis/nerd-fonts/issues/667

**Comment by page-down** [comment]
I can confirm that the updated range is correct.

https://github.com/kovidgoyal/kitty/blob/v0.24.3/nerd-fonts-glyphs.txt#L1042-L1070

**Comment by rqel** [comment]
I noticed we should also add U+E0CA
https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points/_compare/9b2642668f2cf8b268c08edf80ca6994f853fb69...51180d98500a5588b0e78593a2259324f4b5a099

**Comment by page-down** [comment]
Below is a comparison of `nerd-fonts-glyphs.txt` with the documented range differences.

```patch
7,10c7,9
< U+E0B0-U+E0BF
< U+E0C0-U+E0C8
< U+E0CC-U+E0CF
< U+E0D0-U+E0D2
---
> U+E0B0-U+E0C8
> U+E0CA
> U+E0CC-U+E0D2
13c12,13
< U+E5FA-U+E62B
---
> U+E300-U+E3E3
> U+E5FA-U+E62F
16c16
< U+F300-U+F313
---
> U+F300-U+F31C
18c18
< U+F67C
---
> U+F500-U+F8FF
```

I should note that I only tested F300-F31C, the others are not tested yet.

**Comment by kovidgoyal** [comment]
I dont use nerd fonts, so I am not the right person to deal with this. @page-down let me know when you think this PR is ready to merge and I will merge.

**Comment by kovidgoyal** [comment]
On Wed, Mar 02, 2022 at 07:34:02AM -0800, page-down wrote:
> @rqel 
> I have actually tried out all the ranges in my diff above.
> Please update the PR according to the diff, merge and add the missing ranges.
> (Replace commas with newlines, sort in order, and join with commas.)
> 
> @kovidgoyal 
> Please point out if there are any ranges where `symbol_map` should not be used.

There are no limitations on symbol_map, it can be used with any unicode
codepoints.

**Comment by rqel** [comment]
`fc-match -f'%{charset}' Symbols\ Nerd\ Font`

> ```45 23fb-23fe 2665 26a1 2b58 e000-e00a e0a0-e0a3 e0b0-e0c8 e0ca e0cc-e0d2 e0d4 e200-e2a9 e300-e3e3 e5fa-e62f e700-e7c5 f000-f00e f010-f01e f021-f03e f040-f04e f050-f05e f060-f06e f070-f07e f080-f08e f090-f09e f0a0-f0ae f0b0-f0b2 f0c0-f0ce f0d0-f0de f0e0-f0ee f0f0-f0fe f100-f10e f110-f11e f120-f12e f130-f13e f140-f14e f150-f15e f160-f16e f170-f17e f180-f18e f190-f19e f1a0-f1ae f1b0-f1be f1c0-f1ce f1d0-f1de f1e0-f1ee f1f0-f1fe f200-f20e f210-f21e f221-f23e f240-f24e f250-f25e f260-f26e f270-f27e f280-f28e f290-f29e f2a0-f2ae f2b0-f2be f2c0-f2ce f2d0-f2de f2e0 f300-f31c f400-f4a9 f500-fd46```

**Comment by page-down** [comment]
> There are no limitations on symbol_map ...

Yes, it is obvious.

> I don't think some of your listed ranges make sense especially the last range U+F500-U+F8FF

I don't think in this usage scenario the user should be advised to remap non-PUA range characters. So only apply to F8FF.

See my previous link for the actual issues. (`Nerd Fonts 3.0 Roadmap`)

**Comment by page-down** [comment]
@kovidgoyal 
When some glyphs are missing from the font being remapped, does it have no effect?
Any suggestions on how to configure the last range? `U+F500-U+F8FF`

**Comment by kovidgoyal** [comment]
On Wed, Mar 02, 2022 at 07:57:16AM -0800, page-down wrote:
> @kovidgoyal 
> When some glyphs are missing from the font being remapped, does it have no effect?

If not present the usual fallback mechanism is used, see the
font_for_cell() function.

> Any suggestions on how to configure the last range? `U+F500-U+F8FF`

It cant really be configured correctly. Some of those are combining or
other special code points whose semantics are very different from
symbols. So if you assign symbols to them, they may be fine or they may
not depending on what the original codepoint's semantics are. And of
course any regular text using those codepoints will be completely
broken.

**Comment by rqel** [comment]
@page-down 
Also if you have updated the ranges according to `nerd-fonts-glyphs.txt`; some glyphs that included in the current master branch Symbol Nerd Font are not included there. e.g. U+F4A9

**Comment by page-down** [comment]
> ... Some of those are combining or other special code points whose semantics are very different from symbols. ...

So this part can be left alone for now and updated again when nerd fonts 3.0 is released.

> Also if you have updated the ranges according to nerd-fonts-glyphs.txt; some glyphs that included in the current master branch Symbol Nerd Font are not included there. e.g. U+F4A9

Good catch. Then obviously `nerd-fonts-glyphs.txt` needs to be updated (also: gen-wcwidth) , as it affects the unicode input feature.

If you have already done what you care about, then please let us know and this PR can be merged.

**Comment by page-down** [comment]
@rqel 
You may have noticed that there are typos.
`+E0B0-U`, `+E3E3`

> We keep U+E5FA-U+E62B for the last part?

I suggest removing the `U+F500-U+F8FF` part for now. Users who need it can test and add by themselves.

> Also, should I update nerd-fonts-glyphs.txt too?

You can skip that file for now, let's finish this first.

@kovidgoyal 
>> Any suggestions on how to configure the last range? `U+F500-U+F8FF`
>
> It cant really be configured correctly.

I see that there is a `U+F67C` in the current document, so I tried it specifically and found that it renders fine in Konsole (alert icon), but is a vertical line in kitty.
Is this fixable? Or as you say, that is impossible?

**Comment by kovidgoyal** [comment]
On Wed, Mar 02, 2022 at 05:56:44PM -0800, page-down wrote:
> @kovidgoyal 
> >> Any suggestions on how to configure the last range? `U+F500-U+F8FF`
> >
> > It cant really be configured correctly.
> 
> I see that there is a `U+F67C` in the current document, so I tried it specifically and found that it renders fine in Konsole (alert icon), but is a vertical line in kitty.
> Is this fixable? Or as you say, that is impossible?

Actually, now that I look at the numbers more closely the PUA area is
U+E000..U+F8FF so this range should be fine. 
https://en.wikipedia.org/wiki/Private_Use_Areas#Unicode_PUA_blocks

Is this not rendering with symbol_map defined or without? WHat does
--debug-font-fallback output when redering this char?

**Comment by page-down** [comment]
> Is this not rendering with symbol_map defined or without? WHat does
> --debug-font-fallback output when redering this char?

There is no output and it doesn't look like the font is being used?

```shell
kitty --config=NONE -o font_size=16 -o 'symbol_map U+F67C Symbols Nerd Font' --debug-font-fallback fish -c 'printf "%s " \uF67C;echo;read'

# Preloaded font faces: ...
# Symbol map faces: ...
# <END>
```

**Comment by rqel** [comment]
> Look at kovid's comment below, you don't need to remove this section anymore. The ranges you posted are correct.
> 
> >

I fixed those typos, should be good now

**Comment by kovidgoyal** [comment]
Works for me with 

kitty --debug-font-fallback --config NONE -o 'symbol_map U+F67C Symbols Nerd Font' --hold python -c "print('\uf67c ')"

[062 07:56:06.828907] Symbol map faces:
[062 07:56:06.828912] /home/kovid/work/env/conf/fonts/Symbols-2048-em Nerd Font Complete.ttf:0



On Wed, Mar 02, 2022 at 06:19:51PM -0800, page-down wrote:
> > Is this not rendering with symbol_map defined or without? WHat does
> > --debug-font-fallback output when redering this char?
> 
> There is no output and it doesn't look like the font is being used?
> 
> ```shell
> kitty --config=NONE -o font_size=16 -o 'symbol_map U+F67C Symbols Nerd Font' --debug-font-fallback fish -c 'printf "%s " \uF67C;echo;read'
> 
> # Preloaded font faces: ...
> # Symbol map faces: ...
> # <END>
> ```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/pull/4775#issuecomment-1057599169
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________

**Comment by kovidgoyal** [comment]
Screenshot

**Comment by page-down** [comment]
I confirm it works fine. Sorry, that' s another fish bug.

I think we can merge now and everything is fine.

**Pull request merged**
