### PR TITLE
Micro-optimization

### PR DESCRIPTION
**Pull request by Luflosi**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
How is this an optimization?

**Comment by Luflosi** [comment]
When `args.action` is `test`, it isn't checked if it is also `clean` or any of the later options. The compilation database is also not read from disk and written back when `args.action` is `test`. I was also able to get rid of the return statement.
Instead of what I did in this commit, I could also add a `return` to the end of the `if args.action == 'test':` block, if you prefer that.

**Comment by kovidgoyal** [comment]
Nothing beyond os.execlp is executed, the current process gets entirely
replaced by a new one at that point, so there is no need for this.

**Comment by Luflosi** [comment]
Oh, ok, I didn't actually really read that line 😅.
Sorry about the noise then.

**Pull request closed without merging**
