### PR TITLE
Cocoa: Move slightly towards modern Objective-C

### PR DESCRIPTION
**Pull request by Luflosi**
Please double-check that the two lines are actually equivalent. I tested it and it seems to work fine but I'm not entirely sure if this is correct. Is `[title release];` still needed?

### CODE REVIEW

**Comment by Luflosi** [comment]
I guess I need to remove the `[title release];`, right?

**Comment by Luflosi** [comment]
Nope, the error has nothing to do with my code, I think.

**Comment by kovidgoyal** [comment]
yes you should remove release. In cocoa land you only need to release things you have created using alloc/init or retained.

**Comment by Luflosi** [comment]
I fixed it.

**Pull request merged**
