### PR TITLE
add activity_symbol_color config variable

### PR DESCRIPTION
**Pull request by 3nprob**
Allows changing color of `tab_activity_symbol`.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
What's the motivation for this? In general you would use an emoji which is rendered in its own color anyway

**Comment by 3nprob** [comment]
The motivation is I want something else than red, and no, no emoji in my terminal plz

**Comment by kovidgoyal** [comment]
On Thu, Jan 13, 2022 at 09:46:05AM -0800, 3nprob wrote:
> The motivation is I want something else than red, and no, no emoji in my terminal plz

Why no emoji in your terminal, are you allergic?

**Comment by 3nprob** [comment]
> On Thu, Jan 13, 2022 at 09:46:05AM -0800, 3nprob wrote: The motivation is I want something else than red, and no, no emoji in my terminal plz
> Why no emoji in your terminal, are you allergic?

I could ask you if you're allergic to ASCII - call it a matter of preference

**Comment by 3nprob** [comment]
BTW, your solution of allowing templating in `tab_activity_symbol` is a better solution, nice one :+1:

**Pull request closed without merging**
