### PR TITLE
A small doc patch.

### PR DESCRIPTION
**Pull request by teika-kazura**
Hi. I created a small documentation patch. I can't build the doc, so it's not tested. If you like it, please use it. Feel free to modify.

Changes are:

1 Added links to the website (https://sw.kovidgoyal.net/kitty/) and the github repo in index.rst.
2 Mouse pointer config note.
3 Waring about "ssh" kitten; do not use it to forward X.
4 Glossary -> kitten: Added a link to kitten_intro.

Most points must be ok, but the rationale for the point 1 is: I always install the doc locally in my PC. In that case the kitty.png points the local home, not the upstream home.

Thanks a lot for developping kitty. Best wishes.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
1. This should be included only when building locally, its just clutter otherwise.
2. I'm afraid kitty docs are not the place to learn about configuring X11 The XCURSOR env vars are generic X11 config mechanisms supported by many programs
3. X11 forwarding works fine with the ssh kitten
4. This is ok

**Comment by teika-kazura** [comment]
Thanks.

For the mouse cursor, my proposal is legit, since there are many ways to change the cursor for X apps - at least .Xdefaults - but none of them apply to kitty. It took me quite a lot to find it.

Furthermore the mouse pointer size is a faq: https://github.com/kovidgoyal/kitty/issues/4860 https://github.com/kovidgoyal/kitty/issues/6914 https://github.com/kovidgoyal/kitty/issues/7201 . If you are generous enough and don't mind further repeated questions, it's ok, but I doubt if it really will benefit you.

Anyway your decision has to be respected. Let me repeat my gratitude again. Best regards.

**Comment by kovidgoyal** [comment]
Eh, on X11, there are myriad ways to configure mouse cursor size, kitty
currently supports the env var and gnome settings read via DBUS.
See https://wiki.archlinux.org/title/Cursor_themes

I am not particularly interested in documenting this mess. What would be
useful is a patch to read cursor size from xrdb as well and use that
when defined in preference to the env vars on X11.

**Comment by kovidgoyal** [comment]
Actually, I looked at the code, and kitty on X11 uses XCreateFontCursor
which should automatically respect Xcursor.theme and Xcursor.size so
nothing to do. kitty follows standard X11 APIs on X11. On Wayland it
first gets the compositor to draw standard cursors for it, if the
compositor doesnt support that it fallsback to DBUS + env vars.

**Comment by teika-kazura** [comment]
Sorry for making noise, and thank you again for taking extra effort of checking it.
Yes, today Xcursor.theme|size works for me, too

# Last time I tried these two didn't work. It is sure that it was the case for me; at that time all other apps' mouse pointer was changed except kitty, and I was frantic seeking a solution. Strange.

**Pull request closed without merging**
