### PR TITLE
Add AppData manifest file

### PR DESCRIPTION
**Pull request by tim77**
Please add initial AppData manifest file for modern package managers and easy installation on searching via GNOME Software/Discover KDE.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

### CODE REVIEW

**Comment by kovidgoyal** [comment]
kitty does not come with any desktop files/appstream files or any other desktop related metadata. Those can be provided by distro packages if they want it. kitty is a terminal emulator for power users of the command line, desktop files/app stores and the like are not really relevant to its target user base. Hell it does not even have a scrollbar :)

**Comment by tim77** [comment]
Also:

> or any other desktop related metadata

Not really. `.desktop` file = desktop related metadata

**Comment by kovidgoyal** [comment]
On Wed, Oct 23, 2019 at 07:37:53AM -0700, Artem Polishchuk wrote:
> Also:
> 
> > or any other desktop related metadata
> 
> Not really. `.desktop` file = desktop related metadata

There is no .desktop file.

**Comment by tim77** [comment]
> There is no .desktop file.

Jesus Christ... 🤦🏻‍♂️
https://github.com/kovidgoyal/kitty/blob/master/setup.py#L721

**Comment by kovidgoyal** [comment]
You are welcome to contribute the addition of an appdata file to
the code that generates the linux bundle. There is not going to be a
desktop file or an appdata file in kitty's source tree as there are
just useless noise there. Though I dont know what use a generated
appdata file is to anyone anyway, since it will only be dynamically
generated for linux bundles and presumably not help with software
centers or their ilk, though i confess I haven't a clue how they scrape
their metadata.

**Comment by kovidgoyal** [comment]
Sure distros are welcome to add appdata files if they wish. The baseline kitty package is pretty barebones in terms of desktop integration anyway.

**Pull request closed without merging**
