### PR TITLE
Convert TabCWD into str so we can use string method on it

### PR DESCRIPTION
**Pull request by nxvxl**

### CODE REVIEW

**Comment by kovidgoyal** [comment]
The whole point of using TabCWD is so that the cwd is queries only when it is actually needed in a template, by pre-converting it that optimisation is removed use ```{str(cwd)}``` in your template instead.

**Comment by kovidgoyal** [comment]
Actually I decided to implement it more flexibly https://github.com/kovidgoyal/kitty/commit/352c07987b2a39088a2d010a348bbcd743d8a25a

**Comment by nxvxl** [comment]
Thank you for the feedback.

I tried your suggestions but got an error
```
[207 14:06:09.627658] Invalid tab title template: "{index}: {str(cwd).split('/')[-1]}" with error: name 'str' is not defined
```
I only want last part of the path.
Any other advice?

**Comment by nxvxl** [comment]
Cool, thanks!

**Pull request closed without merging**
