### PR TITLE
dont -> don't

### PR DESCRIPTION
**Pull request by Luflosi**
I found every word dont and replaced it with don't. Is there any reason for leaving the apostrophe out?

### CODE REVIEW

**Comment by kovidgoyal** [comment]
The apostrophe is a bit of an anachronism that I personally find useless. The convention of using apostrophes to denote contractions may have made sense when the use of contractions was new -- it doesnt really anymore. That said I dont have any strong feelings about it.

**Comment by kovidgoyal** [comment]
Yeah they are, they were made because of compiler warnings. And are a
good idea in any case. If you care about matching upstream glfw, you
should see about getting them into upstream.

**Comment by Luflosi** [comment]
Thanks.
I'm linking to the place where this comment should have been for future reference: https://github.com/kovidgoyal/kitty/commit/841c907efc643a4f4f06b2686d0d1e6022710600#r34453289

**Comment by kovidgoyal** [comment]
Catches more errors at compile time rather than runtime.

**Pull request merged**
