### PR TITLE
fix(logo): make the icon more inline with Big Sur

### LINKED ISSUE #3547: [minor] New macOS icon is bigger than it should be
**Describe the bug**
New macOS icon is bigger than it should be

**To Reproduce**
1. Make sure you have `0.20.2` version
2. New App icon is bigger than the rest of the apps

**Expected behavior**
To match the macOS guidelines https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

**Screenshots**
Screenshot 2021-04-28 at 12 41 09
Screenshot 2021-04-28 at 12 37 06

**Environment details**
OS: macOS 11.2.3

```
kitty 0.20.2 created by Kovid Goyal
Darwin <redacted machine name> 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.3 BuildVersion:	20D91
Loaded config files: /Users/ahmedelgabri/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color          None
adjust_line_height           2
allow_remote_control         y
background                   Color(red=17, green=17, blue=17)
bold_font                    PragmataPro Mono Liga Bold
bold_italic_font             PragmataPro Mono Liga Bold Italic
clipboard_control            frozenset({'write-primary', 'write-clipboard', 'no-append'})
color0                       Color(red=29, green=31, blue=33)
color1                       Color(red=204, green=102, blue=102)
color10                      Color(red=153, green=204, blue=153)
color11                      Color(red=255, green=204, blue=102)
color12                      Color(red=102, green=153, blue=204)
color13                      Color(red=204, green=153, blue=204)
color14                      Color(red=102, green=204, blue=204)
color15                      Color(red=221, green=221, blue=221)
color2                       Color(red=181, green=189, blue=104)
color3                       Color(red=240, green=198, blue=116)
color4                       Color(red=129, green=162, blue=190)
color5                       Color(red=178, green=148, blue=187)
color6                       Color(red=138, green=190, blue=183)
color7                       Color(red=197, green=200, blue=198)
color8                       Color(red=51, green=51, blue=51)
color9                       Color(red=242, green=119, blue=122)
cursor                       Color(red=32, green=187, blue=252)
cursor_stop_blinking_after   0
enable_audio_bell            False
font_family                  PragmataPro Mono Liga
font_size                    12.0
force_ltr                    True
foreground                   Color(red=197, green=200, blue=198)
hide_window_decorations      1
inactive_tab_background      Color(red=29, green=31, blue=33)
italic_font                  PragmataPro Mono Liga Italic
kitty_mod                    8
macos_custom_beam_cursor     True
macos_option_as_alt          3
macos_thicken_font           1.1
macos_traditional_fullscreen True
rectangle_select_modifiers   1026
scrollback_lines             20000
select_by_word_characters    :@-./_~?&=%+#
strip_trailing_spaces        smart
tab_activity_symbol          ▲
tab_bar_edge                 1
window_alert_on_bell         False
window_margin_width          FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
window_padding_width         FloatEdges(left=10.0, top=10.0, right=10.0, bottom=10.0)
Added shortcuts:
	 ctrl+i KeyAction(func='send_text', args=['application', b'H'])
	 shift+cmd+h KeyAction(func='show_scrollback', args=())
Changed shortcuts:
	 cmd+, KeyAction(func='move_tab_backward', args=())
	 cmd+h KeyAction(func='previous_window', args=())
	 cmd+u KeyAction(func='input_unicode_character', args=())
	 cmd+w KeyAction(func='close_window', args=())
```

**Additional context**

### PR DESCRIPTION
**Pull request by MindTooth**
This tries to follow the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) from Apple.

## Screenshots

Icon-256 

Screen Shot 2021-04-28 at 15 19 18

## Environment

* macOS 11.3
* kitty 0.20.2

## Possible fixes

Fixes #3547.

### CODE REVIEW

**Comment by MindTooth** [comment]
Noticed that this was an old version.  Missing the shadows.

**Comment by MindTooth** [comment]
I need to apply an attribute given the CC BY 4.0 license.  Something that I thought of after I submitted this.

The most ideal place to add?  A small note in the readme, or its own file in the logo folder?

**Comment by kovidgoyal** [comment]
A file in the logo folder would be best I believe.

**Comment by benatshippabo** [comment]
Thanks for doing this @MindTooth ❤️

**Comment by d4vsanchez** [comment]
This is awesome! Current version (0.20.2) icon looks really disproportionate with other icons. Do you know when this change is going to be released?

**Pull request merged**
