### PR TITLE
Add command to disable/enable ligatures per window

### PR DESCRIPTION
**Pull request by blahgeek**
Font ligatures are good for code editing, but not good for some other terminal applications (e.g. htop).

This patch allows user to disable/enable ligatures dynamically, per window.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Looks fine, some feedback:

1) This should store a per window "ligature strategy" variable that should be initialised form the global option

2) There should be a way to define a keyboard shortcut to change the ligature strategy for the current window/tab/all windows

3) The remote control command should allow defining windows to change via  --match option, just like many other commands that affect windows take.

4) Not clear to me why you have exposed dirty_sprite_positions to python code, probably for debugging? That should be removed.

**Comment by blahgeek** [comment]
Thanks for your feedback.

> * This should store a per window "ligature strategy" variable that should be initialised form the global option
> * There should be a way to define a keyboard shortcut to change the ligature strategy for the current window/tab/all windows
> * The remote control command should allow defining windows to change via  --match option, just like many other commands that affect windows take.

OK, I would implement these when I got time.

> 4. Not clear to me why you have exposed dirty_sprite_positions to python code, probably for debugging? That should be removed.

It's for redrawing the screen. Is there a better way already?

**Comment by kovidgoyal** [comment]
Ah I did not notice you were using it in boss.py -- yes, that is the correct way to get kitty to redraw the screen when the option value changes.

**Comment by blahgeek** [comment]
@kovidgoyal updated

**Pull request closed without merging**
