### PR TITLE
Add macos_hide_from_tasks option

### PR DESCRIPTION
**Pull request by cfal**
Adds option for macOS to hide from tasks list. This is useful if you have kitty configured with a global hotkey and don't need to see it when alt tabbing.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Some comments:

1) It needs to default to off
2) What happens if you have more than one kitty window?

**Comment by kovidgoyal** [comment]
As for using a external tool to activate/minimize, doesn't https://www.hammerspoon.org/ work?

**Comment by kovidgoyal** [comment]
You didn't answer (2)? You can open multiple top level windows in kitty (by pressing ctrl+shift+n) Currently your patch will only apply the taskbar skipping to the first window, not subsequent ones.

**Comment by cfal** [comment]
Ah got it. It works correctly as-is because glfw only sets the activation policy once in initializeAppKit(), which is a static method called only when the first window is created:
https://github.com/kovidgoyal/kitty/blob/master/glfw/cocoa_window.m#L1205

**Comment by cfal** [comment]
Done, please take a look. Thanks!

**Comment by BIKA-C** [comment]
When this option is checked, and toggled to fullscreen, the titlebar disappears:

https://user-images.githubusercontent.com/50717946/227764879-2716dde9-62fa-411b-88aa-2b19cabcb887.mp4

**Pull request merged**
