### PR TITLE
Add a makefile

### PR DESCRIPTION
**Pull request by geordieF**
just running make is so nice.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I committed a slightly simpler makefile :)

**Comment by geordieF** [comment]
;)

**Comment by geordieF** [comment]
Actually, if someone (like me) uses fish instead of bash, your doesn't work, but mine does! This is because fish needs context for this kind of stuff.

**Comment by kovidgoyal** [comment]
Really, why does the shell matter? Make does not execute its build commands through a shell.

**Comment by geordieF** [comment]
It seems that fish tries to do makefiles itself, which is faster somehow. This also helps in porting to mac as it expects a global path unless you yo tell it not to.

**Comment by kovidgoyal** [comment]
You saying that invoking make in fish does not call /usr/bin/make? I tried running my Makefile under fish and it worked fine?

**Comment by geordieF** [comment]
That's weird, mine dowsn't work. Must be some obscure setting that I didn't find. I just checked and Yosemite says that it cant fint the file.

**Review by nikrich — APPROVED** [review]

**Pull request closed without merging**
