### PR TITLE
move windows into separate tabs

### PR DESCRIPTION
**Pull request by 0x17de**
This PR allows moving windows away into new tabs and is related to #1310. Merging windows into other tabs could build upon this PR.
Please check my assigned hotkey and maybe propose a different one. So far i thought about e(x)tract (Ctrl+Shift+x). Maybe we can come up with something better, that also supports the other direction of merging windows into existing tabs.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I am travelling for a few days, I will look at this when I return.

**Comment by kovidgoyal** [comment]
This looks generally fine, good job. Some issues:

1)  You have to deal with overlay windows. If the window being moved has an overlay, both the window and its overlay will have to be moved

2) Moving a window into a new tab can in general cause it to be resized, this might be handled automatically, not sure, but should be checked. IN particular if th etab is in a different os window which has a different font size -- this of course does not happen with your current code, but can in general.

3) I would like to make the action more general so rather than move_window_to_tab one should have instead a detach_window command that takes arguments and allows the window to be moved to a specific tab/OS window. This can be done after the basic PR is merged, however.

**Comment by kovidgoyal** [comment]
I have merged the state.c part of your PR. I want to think about a better api for detaching and placing windows in boss.py/tabs.py when I get that done we can add controls for it as desired.

**Comment by kovidgoyal** [comment]
I have added a pair of detach_window()/attach_window() functions that should serve as a general API for moving windows between tabs.

**Comment by kovidgoyal** [comment]
And I have added a _move_window_to() function to boss.py that serves as an API for moving windows to existing or new tabs.

**Comment by vdimir** [comment]
Could you tell please, if it was included to any release? Cannot find this feature in the current one.

**Comment by kovidgoyal** [comment]
Yes it has, years ago. look for detach_window

**Pull request merged**
