### PR TITLE
Change size_t_min static function in kitty/ringbuf.c to static inline

### PR DESCRIPTION
**Pull request by ChungHsuanChen**
Change static function  size_t_min in kitty/ringbuf.c to static inline function and move to kitty/ringbuf.h for simplifying .c file

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I dont understand the motivation of this. Moving the function into a
header file doesnt simplify anything and in fact means that the function
has to now be parsed by the compiler for every translation unit the header
file is included in.

**Comment by ChungHsuanChen** [comment]
The motivation of moving this function to header file is that making c file "only" contain implementation about ringbuf. Other function in ringbuf.c is correlated with struct ringbuf_t.
Making it an inline function is because it will have some overheads, such as read parameter from stack ,read register. Although size_t_min function only calls 10 times in ringbuf.c, it will affect performance if the function is called many times in the future without inline function or a macro.

**Comment by kovidgoyal** [comment]
On Sat, Apr 09, 2022 at 07:08:03PM -0700, ChungHsuanChen wrote:
> The motivation of moving this function to header file is that making c file "only" contain implementation about ringbuf. Other function in ringbuf.c is correlated with struct ringbuf_t.

It's a utility function used by other functions in that .c file. And
only there, as such, it belongs there.

> Making it an inline function is because it will have some overheads, such as read parameter from stack ,read register. Although size_t_min function only calls 10 times in ringbuf.c, it will affect performance if the function is called many times in the future without inline function or a macro. 

inlining in modern compilers is decided by the compiler, the inline
keyword doesn't influence the compiler's decision on this.

**Comment by ChungHsuanChen** [comment]
Yes, I understand. Making this function a macro will it be more resonable?

**Comment by kovidgoyal** [comment]
You could, but it wont make any actual difference, since I am pretty sure every compiler will inline that function call anyway. And using an actual function means nicer ergonomics than a macro. Macros are useful only when you need to run the code for variables of different types, which is not the case here.

**Comment by ChungHsuanChen** [comment]
I see. From my understanding, macro will be handled by preprocessor not compiler. Won't it be beneficial or not?

**Comment by kovidgoyal** [comment]
No, it wont. The actual assembly generated in both cases will be
identical.

**Pull request closed without merging**
