### PR TITLE
Add padding options for around the tab bar

### PR DESCRIPTION
**Pull request by jsphnecclia**
```
The margin to the top or bottom of the tab bar (in pts)
If tab_bar_style is hidden, this value has no effect.
If the number of tabs is less than tab_bar_min_tabs, this is the distance between the top of the os window and
the point where the padding/margin set through window_margin_width or window_padding_width takes over.
If the number of tabs is greater than tab_bar_min_tabs, there is the top of the os window, a padding of tab_bar_margin_height,
the tab bar (which takes a height of one character cell), the padding/margin set through the methods mentioned above, and
then the shell prompt.
```

Edit tab_bar_margin_height in kitty.conf to see the effect (defaults to 0.0)

(reworked os_window_regions to not evaluate unnecessary conditions in this feature, when the tab bar style is set to hidden)

[See Issue](https://github.com/kovidgoyal/kitty/issues/3247)

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Why should this option apply when the tab bar is hidden because there are not enough tabs?

**Comment by jsphnecclia** [comment]
The assumption was that if the tab style was not set to hidden, then the margin when the tab bar is hidden would be no less than the margin of the tab bar when it is shown. 
Screen Shot 2021-04-03 at 12 13 31 PM

Important to note: By default the window padding or margin set in window_margin_width and window_padding_width is the margin or padding below (or above) the tab bar. 
Screen Shot 2021-04-03 at 12 22 12 PM


Setting it this way also has the effect of removing a ghost/duplication of the prompt, seen below:
Screen Shot 2021-04-03 at 12 20 05 PM
Resizing the os_window also gets rid of this duplication. We can get rid of your complaint, add more customization, and fix this bug all at once if there were a way to isolate what part of the resizing functionality we need to replicate and place it in the correct create_tab function. I wasn't able to isolate this function when I tried my hand at it earlier

**Comment by jsphnecclia** [comment]
(PS: And more concisely as an answer to why there would be a difference between tab_style hidden and a tab hidden by being less than min_tabs is precisely that the former setup would never see a tab bar and thus window_padding_width/window_margin_width would have the reasonable effect desired, while the latter setup is designed to allow for a case either with or without the tab bar. This causes problems that weren't there in the tab_style route: specifically that window_margin_width/window_padding_width is interpreted in some cases as distance from the os_window, and in some cases as the distance from the tab_bar.)

**Comment by kovidgoyal** [comment]
You cant just change the central region position/size. When you decrease its size it means nothing is going to be drawn where it was drawn before. Which is the cause of the rendering artifacts you found, whatever was in the back buffer at that location previously, is being drawn. Normally the tab bar will render in the space left for it. If you add extra space you have to have something that will render in that space. 

You will need to call add_borders_rect() in borders.py around line 83 to cover the rectangle created by the extra padding. And please change it so that the behavior is the same regardless of how the tab bar is hidden. Its not really intuitive to have it behave differently in the two cases.

**Comment by jsphnecclia** [comment]
I've tried adding border rect in both tab_bar.py and borders.py, to no effect. I'm not sure how add_borders_rect() (in borders.py) works. I've looked over the code but when I try to implement it by adding `add_borders_rect(self.os_window_id, self.tab_id, 0, 0, 0, 100, BorderColor.default_bg)` after the `if not has_background_image` block, I still get the same rendering artifacts

**Comment by kovidgoyal** [comment]
Oh yeah my mistake, sorry. border_rects is used only for in tab
contents. The tab bar lives outside all tabs. You will have to do it the
hard way by changing line 624 in child-monitor.c to call draw_borders()
for the padding region.

**Comment by jsphnecclia** [comment]
What would the inside of that call to draw_borders() look like? 

I was testing around trying to figure it out and I got this:

`draw_borders*br->vao_idx, br->num_border_rects, br->rect_buf, br->is_dirty, os_window->viewport_width, 100, active_window_bg, num_visible_windows, all_windows_have_same_bg, os_window);`

But all it does is now the entire prompt is flickering in the visual artifacts rather than just the cursor, as before.

**Comment by kovidgoyal** [comment]
draw_borders() draws rectangles represented by the BorderRects and a vertex array object (vao_idx). Currently the vao and rects are stored per tab. You will have to add another pair of these to the OSWindow object and add the actual rectangles for the new padding region. See add_border_rext in state.c for an example.

**Comment by jsphnecclia** [comment]
So I'll be adding a vao and rects to OSWindow for the area around (but not in) the tab bar in the child_monitor file, and a new version of add_borders_rect (say add_tab_bar_rect) in the state.c file?

**Comment by kovidgoyal** [comment]
On Tue, Apr 06, 2021 at 10:38:03AM -0700, jsphnecclia wrote:
> So I'll be adding a vao and rects to OSWindow for the area around (but not in) the tab bar in the child_monitor file, and a new version of add_borders_rect (say add_tab_bar_rect) in the state.c file?

Basically, yes.

**Comment by jsphnecclia** [comment]
I can't seem to find the declaration of OSWindow / where would I put the vao and rects otherwise?

**Comment by kovidgoyal** [comment]
state.h

**Comment by jsphnecclia** [comment]
Ah, thank you. I'm not used to this python/c hybrid.

I've been working some more on the different methods you have mentioned in your replies. I've tried several different paths, but each with no success.

in state.c:
Screen Shot 2021-04-09 at 8 38 15 PM
Later:
`KIIIII(add_tab_bar_padding_rect)`
and later:
`MW(add_tab_bar_padding_rect, METH_VARARGS)`

(brings up the following error: 
Screen Shot 2021-04-09 at 6 35 07 PM)


also, in state.c , I tried this in add_os_window(), to no success:
    `ans->tab_bar_padding_render_data.vao_idx = create_cell_vao();`

I then tried to make a set_tab_bar_padding_render_data, with no success:
Screen Shot 2021-04-09 at 8 51 35 PM

I also gave OSWindow in state.h a border_rects and a ScreenRenderData tab_bar_padding_render_data. I think at least these are right. but I used these in child-monitor.c to no effect. I tried to place set_tab_bar_padding_render_data in the layout() function there (among other places such as the borders.py file), again with no luck :(.

I've reached a dead end. If you could give a simple example of an (even partial) fix for this rendering artifact (partial meaning a fix that covers up only part of the artifact), I should be able to implement the rest of the patch no problem.

(I committed a version that showcases the rendering artifact. Use `tab_bar_margin_height 19.0` and `window_padding_width 8.0 27.0 27.0 ` in kitty.conf to test an instance of the bug)

**Comment by Luflosi** [comment]
You should rebase your commits onto master instead of merging with master.

**Comment by jsphnecclia** [comment]
Ahh sorry, I think I fixed that just now, but I'm not sure.

**Comment by jsphnecclia** [comment]
Fairly certain I botched this PR/rebase :/ I'm going to try another time from a fresh fork

**Comment by Luflosi** [comment]
The commits from before you last force-pushed are still available on GitHub.

**Comment by jsphnecclia** [comment]
I think the issue I'm having/seeing is that config_data.py has been moved somewhere else?

**Comment by jsphnecclia** [comment]
So its trying to send in the whole config_data.py file. The rest of the commits are as they should be, I think

**Comment by jsphnecclia** [comment]
I have it mainly transfered to the new scheme, however using pt_to_px no longer works from inside state.c, breaking my feature. Is there a way to get around this?

**Pull request closed without merging**
