### PR TITLE
Fix white background color not allowing transparency

### LINKED ISSUE #1285: Semi-transparency does not work with colors other than black.
I am trying to use a white background with 50% opacity, but it only becomes transparent when I configure it to 0 opacity.

### PR DESCRIPTION
**Pull request by Luflosi**
Fixes #1285.
I played around with the cell_fragment shader code some more and while I don't really understand what's going on, this patch fixes the issue (while introducing a slight problem, which you should look at, I'll explain it later). This patch essentially undoes 074614bc8e940725939aa7a316f0a7086e01e05c and 96229becd1bef8bd69b412e61fac96146300646e except that it multiplies except of dividing. `final_color`, the result of the computation seems to need pre-multiplication and `final_color` before my new multiplication seems to not be pre-multiplied. Otherwise I can't explain why this patch works.
Here are some screenshots with various `background_opacity` settings and `background #ffffff` and `background #000000` colors in `kitty.conf` with and without the fix in front of a checkerboard pattern:

- Without the fix
  - `background #000000`
    - `background_opacity 1.0`
black 1 0
    - `background_opacity 0.5`
black 0 5
    - `background_opacity 0.0`
black 0 0
  - `background #ffffff`
    - `background_opacity 1.0`
white 1 0
    - `background_opacity 0.5`
white 0 5
    - `background_opacity 0.0`
white 0 0
- With the fix
  - `background #000000`
    - `background_opacity 1.0`
black 1 0
    - `background_opacity 0.5`
black 0 5
    - `background_opacity 0.0`
black 0 0
  - `background #ffffff`
    - `background_opacity 1.0`
white 1 0
    - `background_opacity 0.5`
white 0 5
    - `background_opacity 0.0`
white 0 0

Here is the problem: If you look closely at the bottom-right side of the left triangle in the bottom screenshot (a little less noticeable in the screenshot above that), you can see, that anti-aliasing is creating a few while-ish pixels where there should only be different mixes of blue and transparent ones, letting the black background shine through. That also happens with the other triangle but that isn't visible because of the white color behind the kitty window in that spot. I also think this is happening with the text but I'm not sure. That would mean, that #1005 is only partially fixed.

If my theory at the top with the pre-multiplication is correct, that means, that `alpha_blend_premul()` is taking the pre-multiplied (according to one comment in the code) color from `calculate_foreground()` and converting it to non-pre-multiplied color. I furthermore assume, that the `vec4` datatype uses values 0-255 for the color information. That would explain the weird white pixels because the back and forth calculation looses some color information.

There are also still some other issues with transparency like the weird borders with white background color but that should be looked at another time IMHO since I find #1005 and #1285 being fixed more important for now.

Wow, this pull request took several hours to create with all the testing and screenshots and the text and stuff 😅.

### CODE REVIEW

**Comment by Luflosi** [comment]
Wait, don't merge this yet, maybe I found a different solution:
```diff
diff --git a/kitty/cell_fragment.glsl b/kitty/cell_fragment.glsl
index 971b2881..504ea9ec 100644
--- a/kitty/cell_fragment.glsl
+++ b/kitty/cell_fragment.glsl
@@ -101,7 +101,7 @@ void main() {
 #else
     // SIMPLE
 #ifdef TRANSPARENT
-    final_color = alpha_blend_premul(fg.rgb, fg.a, background, bg_alpha);
+    final_color = alpha_blend_premul(fg.rgb, fg.a, background * bg_alpha, bg_alpha);
     final_color = vec4(final_color.rgb, final_color.a);
 #else
     // since background alpha is 1.0, it is effectively pre-multiplied
```
I don't think `background` is pre-multiplied, so I just did that and everything I tested so far seems to work fine. I'll make a new commit tomorrow if you don't mind and create another bunch of screenshots if you like.

**Comment by kovidgoyal** [comment]
That would break #1221

**Comment by kovidgoyal** [comment]
vec4 is a floating point type, so stores alpha as number between 0 and 1.

**Comment by Luflosi** [comment]
Can #1221 be fixed in a different way? I think the way you fixed it was wrong.

**Comment by Luflosi** [comment]
I did that, can you please review and merge if everything is good?

**Pull request merged**
