### PR TITLE
Fix message recursion between wayland compositor (#5360)

### PR DESCRIPTION
**Pull request by wengxt**
1. Only update preedit if preedit changed.
2. Only send cursor update if cursor position is not changed.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I dont follow the need for this. kitty already doesnt send anything in response to done events.

**Comment by wengxt** [comment]
> I dont follow the need for this. kitty already doesnt send anything in response to done events.

the reason is that it’s triggered by preedit update when preedit is same. not explicitly reply anything to done.

**Comment by kovidgoyal** [comment]
On Thu, Aug 11, 2022 at 06:52:57PM -0700, Weng Xuetian wrote:
> > I dont follow the need for this. kitty already doesnt send anything in response to done events.
> 
> the reason is that it’s triggered by preedit update when preedit is same. not explicitly reply anything to done.

But does that actually cause an infinite recursion? And if so, why? And
why does it not show up under mutter?

**Comment by wengxt** [comment]
> On Thu, Aug 11, 2022 at 06:52:57PM -0700, Weng Xuetian wrote: > I dont follow the need for this. kitty already doesnt send anything in response to done events. the reason is that it’s triggered by preedit update when preedit is same. not explicitly reply anything to done.
> But does that actually cause an infinite recursion? And if so, why? And why does it not show up under mutter?

Sorry, but I can easily reproduce it under mutter. You need to use an input method that has preedit.

**Comment by wengxt** [comment]
Upload a video as proof.
https://user-images.githubusercontent.com/259684/196316515-e0509b43-b009-4919-9953-248d54ad31a3.mp4

**Comment by kovidgoyal** [comment]
> > On Thu, Aug 11, 2022 at 06:52:57PM -0700, Weng Xuetian wrote: > I dont follow the need for this. kitty already doesnt send anything in response to done events. the reason is that it’s triggered by preedit update when preedit is same. not explicitly reply anything to done.
> > But does that actually cause an infinite recursion? And if so, why? And why does it not show up under mutter?
> 
> Sorry, but I can easily reproduce it under mutter. You need to use an input method that has preedit.

Then please specify how I can reproduce it. Which input method, and what kep presses to trigger it.

**Comment by kovidgoyal** [comment]
Ok I'll take a look at this a little later, thanks.

**Pull request merged**
