### PR TITLE
Use a python f'' string instead of string.format()

### PR DESCRIPTION
**Pull request by Luflosi**
I think this is a bit more readable.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
f strings are not available in python 3.5

**Comment by Luflosi** [comment]
Ok, sorry.

**Comment by bew** [comment]
Could we update the minimal python version?

**Comment by kovidgoyal** [comment]
Someday, sure.

**Comment by Luflosi** [comment]
Python 3.5 is no longer supported according to https://devguide.python.org/#status-of-python-branches. Support was ended on 2020-09-13. Is now the time to update the minimal version to 3.6?

**Comment by kovidgoyal** [comment]
The minimum python version is already 3.6

**Comment by Luflosi** [comment]
I missed that, sorry.

**Pull request closed without merging**
