### PR TITLE
Add default choice option for ask kitten

### PR DESCRIPTION
**Pull request by page-down**
Add default choice option for ask kitten.
Press Enter to select the default, Esc to select nothing (Ctrl+C).
Make the `No` click range the same as `Yes` for easy clicking.
Makes the default take effect for text input, applied in set_tab_title action.
The tab title can be cleared, and the window title will be used again.
Set reasonable default choice for some features that use ask kitten.

However, my personal preference for quit confirmation is still `No` as the default.

Please review if there are any problems, thank you.

### CODE REVIEW

**Comment by page-down** [comment]
I found some issues with hyperlink's ask.

```shell
kitty --config=NONE -o allow_hyperlinks=ask
```

The position for the url after the line break is odd. There is a very large indent.

```text
What would you like to do with this URL:
                                        file:///...
```

Options cannot be clicked with the mouse.

**Comment by kovidgoyal** [comment]
Hyperlink issue has been fixed and clicking options with the mouse works for me

**Comment by page-down** [comment]
Thanks. Clicking is working fine after fixing the hyperlink multi-line text.

It looks much better now.

---

kitty/boss.py
```python
def on_kitten_finish(
    # ...
        data = deserialize(output)
        if data is None:
            data = default_data
        if data is not None:
```

Is `default_data` working properly? Since Ctrl+C doesn't seem to cause the output to be empty. (Unless killed.)
Also is it necessary to check the kitten exit code?

**Comment by kovidgoyal** [comment]
default_data is for when the window is closed, aka the kitten gets no
chance to respond. It should continue to work, see the confirm()
function.

**Comment by kovidgoyal** [comment]
Or doe you mean for type=choices it might be broken there, havent checked,

**Comment by kovidgoyal** [comment]
This should take care of the choice kitten: https://github.com/kovidgoyal/kitty/commit/32e31a3c6bbebb602ca3eb85853e1a7a4c6d6461

**Comment by page-down** [comment]
Thanks, it's working fine now.

I also thought about whether to select the first one by default, but at the time I thought a truthful answer '<empty>' would be most appropriate, i.e. the user does not make any choice and let subsequent programs choose how to handle it based on that.

But it seems to be unnecessary, just provide a default option.

**Comment by page-down** [comment]
> default_data is for when the window is closed, aka the kitten gets no chance to respond.

You mean Ctrl+C doesn't use default_data, right? (Yes, according to the code.)

If I use `default_data={'response': 'c'}` for testing, hyperlink will not be copied to the clipboard after Ctrl+C. Only after Ctrl+Shift+W closes the window. So it works as expected.

In the recent changes, the default choice are marked using yellow, but I am not sure if green is the default or yellow is the default. Is it appropriate to use underline?

**Comment by kovidgoyal** [comment]
On Fri, Jan 21, 2022 at 11:00:13PM -0800, page-down wrote:
> > default_data is for when the window is closed, aka the kitten gets no chance to respond.
> 
> You mean Ctrl+C doesn't use default_data, right? (Yes, according to the code.)
> 
> If I use `default_data={'response': 'c'}` for testing, hyperlink will not be copied to the clipboard after Ctrl+C. Only after Ctrl+Shift+W closes the window. So it works as expected.

That's not the purpose of default_data, so dont do that. In any case, I
have implemented a choose() method to make using it easier.

> 
> In the recent changes, the default choice are marked using yellow, but I am not sure if green is the default or yellow is the default. Is it appropriate to use underline?

Sure, good idea.

**Comment by page-down** [comment]
I also found a problem where the click is not responsive until the mouse is moved.

For example, if you move the mouse to the No button position first, then press Cmd+Q and click the mouse, you cannot cancel the exit.

Is this something that can be fixed?

**Pull request merged**
