### PR TITLE
Add a --hyperlink-only-matches flag to hyperlinked_grep

### PR DESCRIPTION
**Pull request by groves**
If it's active, only matching lines get links, not file headers or context lines.

I have a kitten that steps through the links it finds to open them like "Find Next" when searching for text in a browser. It's way more useful if the links are only to the lines the search hits, which is what this flag enables.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
Add some docs for this to hyperlinked_grep.rst

**Comment by page-down** [comment]
I would suggest adding a prefix to the kitten options, just like the `ssh` kitten.
Reduce the possibility of adding options with the same name from upstream.

It would be nice if this option could accept more than one value. (all,file_path,context_line,match_line,match_text)
For example, you can add hyperlinks to file paths and matching lines.
The default is to add hyperlinks to all lines.

```shell
kitty +kitten hyperlinked_grep --kitten hyperlink=file_path --kitten hyperlink=match_text
```

If there are examples in the documentation, then the user will know how to use it with other ripgrep options, such as `rg --context`.

**Comment by groves** [comment]
> Add some docs for this to hyperlinked_grep.rst

Done.

> I would suggest adding a prefix to the kitten options, just like the `ssh` kitten. Reduce the possibility of adding options with the same name from upstream.

I was thinking the `hyperlink` prefix was serving the same purpose of avoiding collisions. I prefer it as it makes parsing and cleanup simpler.

> It would be nice if this option could accept more than one value. (all,file_path,context_line,match_line,match_text) For example, you can add hyperlinks to file paths and matching lines. 

I can't think of a reason why I'd want those other options. Do you have a use in mind?

**Comment by page-down** [comment]
> I was thinking the `hyperlink` prefix was serving the same purpose of avoiding collisions.

I don't think so. What prevents conflicts is the `-only-matches` part.
In the docs:
> Hopefully, someday this functionality will make it into some upstream grep program ...

So someday `--hyperlink` might be introduced upstream like `ls --hyperlink`.

This `boolean set` option is too limited and cannot be extended.

For all kitten wrapping another program, having uniform parameters for configuring additional options would reduce the user's cognitive and ease of use, and would not require each kitten to implement its own argument parsing logic.

So the user clearly knows that it's for kitten, not ripgrep.

**Comment by kovidgoyal** [comment]
Merged, with a few minor changes.

**Pull request merged**
