### PR TITLE
Fixes traditional fullscreen hide for Mac OS >= 10.15

### PR DESCRIPTION
**Pull request by npearson72**
Resolves issue described here:

https://github.com/kovidgoyal/kitty/issues/4472

All credit goes to @page-down

### CODE REVIEW

**Comment by page-down** [comment]
I don't think you should remove the original comment.
Additional comments about this change should be appended.

**Comment by kovidgoyal** [comment]
Change the number from 10.15 to 105.whatever the latest minor release of 10.15 is, because this didnt work with 10.15.0

**Comment by npearson72** [comment]
> Change the number from 10.15 to 105.whatever the latest minor release of 10.15 is, because this didnt work with 10.15.0

Good call. I re-built, tested, and confirm it works on `10.15.7`.

Thanks.

**Comment by npearson72** [comment]
🙏 ❤️ @kovidgoyal and @page-down

**Pull request merged**
