### PR TITLE
Issue with MacOS build

### PR DESCRIPTION
**Pull request by cema-sp**
Hi, I had a few issue with MacOS build.
Having `python3` and `glfw` installed via **homebrew** and trying to build **kitty**, I faced the following error: https://gist.github.com/cema-sp/074b5422a0f6ce345f44b3163dad90a4

I played a little with _setup.py_ and found that "framework" python doesn't properly links on build.
And `LINKFORSHARED` has invalid value for brewed **python3**.

Anyone had similar issues? Any suggestions?

### CODE REVIEW

**Comment by kovidgoyal** [comment]
What does

```
python3 -m sysconfig
```

output on your system?

**Comment by cema-sp** [comment]
Here it is: https://gist.github.com/cema-sp/fbdf0271036618956bd2234807ebb01d

**Comment by kovidgoyal** [comment]
According to that the path setup.py is using is correct, `-F/usr/local/Cellar/python3/3.6.0/Frameworks` so I'm not sure why linking is failing. Framework builds are the recommended way to link python on OS X, so I dont think the solution is to turn off frameworks.

**Comment by kovidgoyal** [comment]
Also, many other users have built kitty against python from brew, see #5

Maybe your python install is corrupted, try re-installing it from brew.

**Comment by cema-sp** [comment]
Closed. New pull-request: #41

**Pull request closed without merging**
